"""Keil integration helpers."""

from src.core.keil.discovery import (
    IMPORTANT_UVSC_EXPORTS,
    KeilDiscovery,
    KeilFile,
    discover_keil,
    read_pe_exports,
)
from src.core.keil.project import (
    KeilGroup,
    KeilProject,
    KeilProjectFile,
    KeilTarget,
    find_keil_projects,
    parse_keil_project,
    project_summary_lines,
)
from src.core.keil.uvsock import (
    KeilProcess,
    UvscConnectionResult,
    UvscLaunchPlan,
    UvscLaunchResult,
    UvscLoadResult,
    UvscPreflight,
    UvscSmokeResult,
    attempt_existing_uvsock_connection,
    build_uvision_uvsock_command,
    check_uvsock_preflight,
    list_running_uvision,
    load_uvsc_library,
    run_uvsock_smoke,
    start_uvision_uvsock,
    uvsc_status_name,
)

__all__ = [
    "IMPORTANT_UVSC_EXPORTS",
    "KeilDiscovery",
    "KeilFile",
    "KeilGroup",
    "KeilProcess",
    "KeilProject",
    "KeilProjectFile",
    "KeilTarget",
    "UvscConnectionResult",
    "UvscLaunchPlan",
    "UvscLaunchResult",
    "UvscLoadResult",
    "UvscPreflight",
    "UvscSmokeResult",
    "attempt_existing_uvsock_connection",
    "build_uvision_uvsock_command",
    "check_uvsock_preflight",
    "discover_keil",
    "find_keil_projects",
    "list_running_uvision",
    "load_uvsc_library",
    "parse_keil_project",
    "project_summary_lines",
    "read_pe_exports",
    "run_uvsock_smoke",
    "start_uvision_uvsock",
    "uvsc_status_name",
]
